version: "3"
services:

  db:
    image: mysql
    ports:
      - "32000:3306"
    command: --init-file /db/init.sql
    volumes:
        - ./db/init.sql:/db/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: 127.0.0.14
        MYSQL_DATABASE: f1database
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'pass'
