version: "3"
services:

  db:
    image: mysql
    ports:
      - "32000:3306"
    command: --init-file /db/schema.sql | /db/data.sql
    volumes:
        - ./db/schema.sql:/db/schema.sql
        - ./db/data.sql:/db/data.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: 127.0.0.14
        MYSQL_DATABASE: f1database
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'pass'
